### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by luposlip** [fractalLabs/lein-repetition-hunter#1]
Hi there,

When I run `lein repetition-hunter` I get this error:

```
clojure.lang.Compiler$CompilerException:
java.io.FileNotFoundException: Could not locate clojure/tools/namespace/find__init.class or clojure/tools/namespace/find.clj on classpath., compiling:(leiningen/repetition_hunter.clj:1:1)
```

I've tried to add this to the dependencies, without any changes to above issue:
`[org.clojure/tools.namespace "0.2.11"]`

Best,
Henrik

**Comment by nez** [comment]
Thanks man, you are right `[org.clojure/tools.namespace "0.2.11"]` was missing so I just added it.

Also I had not documented that `[repetition-hunter "1.0.0"]` is needed in the `:dependencies` vector

I deployed the fix to clojars and it works in my clean environment, please let me know if it doesnt in yours

**Comment by luposlip** [comment]
OK, so with the new snapshot pulled from clojars it works better. Now I get the following output:

```
Hunt failed
Cannot open <nil> as a Reader.
```

**Comment by nez** [comment]
@luposlip are you attempting to do `lein repetition-hunter` in an open source project I could try to replicate?
Does it work in a clone of this repo?

I will implement a Debug flag to be able to see more details on the problem

**Comment by luposlip** [comment]
I've just tried in https://github.com/enterlab/rente and https://github.com/enterlab/cordevicljs. In those it works perfectly.
The project I have where it doesn't work, unfortunately isn't open source. I'll see if I can disable stuff in my project.clj until it (hopefully) works.

**Comment by nez** [comment]
Hi @luposlip that error comes up when we feed a namespace that somehow is not available

To mitigate this situation I made the following improvements:

With `DEBUG=y lein repetition-hunter yo can` see the string `Analyzing (namespace1 ns2 ns3)` so we can check if somehow namespaces that are not avialable are being listed.

Also you can now explicitly define which namespaces will be analyzed instead of all of them, just by appending the namespaces as is shown in the readme.

I think maybe we should check if exception handling can be done upsteam on repetition-hunter, maybe ignoring the problematic namespaces instead of just crashing.
